### ISSUE TITLE
Add quality as transform parameter?

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/imagecow#19]
I have some images in a project that need to have more quality than others.

There are any way to pass the quality parameter from `transform` options?

I'm using a stylecow wrapper and is the easiest way to customize some thumbnails from template without need a coder (like sizes).

Thanks!

**Comment by oscarotero** [comment]
Currently the available functions [are these](https://github.com/oscarotero/imagecow/blob/master/src/Image.php#L556). There is a [setCompressionQuality](https://github.com/oscarotero/imagecow/blob/master/src/Image.php#L381) method but it's not available in transform.
To add this method to transform, there are different aproaches:
* Add a second argument to `format`, so you can do `format,jpg,85|resize,300`. The problem with this is you have to call to `format` even if you don't need it (because your image is jpg already).
* Add the `setCompressionQuality` method as is. This generates the ugly: `setcompressionquality,85|format,jpg|resize,300`.
* Rename the function to just `quality`, so the code is `quality,80|format,jpg|resize,300`.

**Comment by eusonlito** [comment]
:+1:
